FROM alpine:latest

RUN apk add \
    texmf-dist \
    texlive \
    texmf-dist-pictures \
    texmf-dist-science \
    texmf-dist-bibtexextra \
    texmf-dist-pstricks \
    texmf-dist-publishers \
    texmf-dist-latexextra
