#!/usr/bin/env bash
# Check if docker is installed
if ! docker -v > /dev/null; then
  echo "docker is not installed. Please install docker."
  exit 1
fi

# Make sure that latex image is created
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && cd ../latex && pwd )"
source $DIR/init.sh ""

# Go to the right directory (do it in the host not docker to allow access to ../file
CUR_DIR=`pwd`
LATEX_DIR=`pwd`
LATEXMK_CMD='latexmk'
for ARG in $@; do
  if [ -f $ARG ]; then
    LATEX_DIR="$( cd "$( dirname "$ARG" )" >/dev/null 2>&1 && pwd )"
    LATEXMK_CMD+=" -pdf $( basename "$ARG" )"
  else
    LATEXMK_CMD+=" $ARG"
  fi
done

# Run latexmk
cd $LATEX_DIR
docker run --rm -it -v "$PWD":/data -w /data latex /bin/sh -c "$LATEXMK_CMD"
cd $CUR_DIR
