[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'haya14busa/dein-command.vim'
depends = ['dein.vim']
[[plugins]]
repo = 'arcticicestudio/nord-vim'
hook_add = '''
  let g:nord_bold_vertical_split_line = 0
  let g:nord_italic_comments = 0
  au MyAutoCmd VimEnter * nested colorscheme nord
'''
[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = 'source ~/.vim/userautoload/plugins/defx.rc.vim'
[[plugins]]
repo = 'scrooloose/nerdcommenter'
[[plugins]]
repo = 'Raimondi/delimitMate'
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/.vim/userautoload/plugins/denite.rc.vim'
[[plugins]]
repo = 'Shougo/context_filetype.vim'
[[plugins]]
repo = 'simeji/winresizer'
[[plugins]]
repo = "machakann/vim-highlightedyank"
[[plugins]]
repo = "christoomey/vim-tmux-navigator"
[[plugins]]
repo = 'mbbill/undotree'
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = 0
hook_add = 'source ~/.vim/userautoload/plugins/coc.rc.vim'
[[plugins]]
repo = 'neoclide/coc-denite'
depends = ['coc.nvim']
# [[plugins]]
# repo = 'dense-analysis/ale'
# hook_add = 'source ~/.vim/userautoload/plugins/ale.rc.vim'
