[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'haya14busa/dein-command.vim'
depends = ['dein.vim']
[[plugins]]
repo = 'arcticicestudio/nord-vim'
hook_add = '''
  let g:nord_italic = 1
  let g:nord_italic_comments = 1
  let g:nord_comment_brightness = 15
  au MyAutoCmd VimEnter * nested colorscheme nord
'''
[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = 'source ~/.vim/userautoload/plugins/defx.rc.vim'
[[plugins]]
repo = 'scrooloose/nerdcommenter'
[[plugins]]
repo = 'Raimondi/delimitMate'
[[plugins]]
repo = 'w0rp/ale'
hook_add = 'source ~/.vim/userautoload/plugins/ale.rc.vim'
[[plugins]]
repo = 'maximbaz/lightline-ale'
hook_add = 'source ~/.vim/userautoload/plugins/lightline-ale.rc.vim'
depends = ['lightline', 'ale']
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/userautoload/plugins/lightline.rc.vim'
[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
build = 'bash install.sh'
hook_add = 'source ~/.vim/userautoload/plugins/language-client.rc.vim'
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/.vim/userautoload/plugins/denite.rc.vim'
[[plugins]]
repo = 'Shougo/context_filetype.vim'
[[plugins]]
repo = 'simeji/winresizer'
[[plugins]]
repo = "machakann/vim-highlightedyank"
[[plugins]]
repo = "edkolev/tmuxline.vim"
hook_add = 'source ~/.vim/userautoload/plugins/tmuxline.rc.vim'
[[plugins]]
repo = "christoomey/vim-tmux-navigator"
[[plugins]]
repo = 'Shougo/echodoc.vim'
hook_add = 'source ~/.vim/userautoload/plugins/echodoc.rc.vim'
[[plugins]]
repo = 'mbbill/undotree'
