[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'haya14busa/dein-command.vim'
depends = ['dein.vim']
[[plugins]]
repo = 'arcticicestudio/nord-vim'
hook_add = '''
  let g:nord_italic_comments = 0
  au MyAutoCmd VimEnter * nested colorscheme nord
'''
[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = 'source ~/.vim/userautoload/plugins/defx.rc.vim'
[[plugins]]
repo = 'scrooloose/nerdcommenter'
[[plugins]]
repo = 'Raimondi/delimitMate'
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/userautoload/plugins/lightline.rc.vim'
depends = ['nord-vim']
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/.vim/userautoload/plugins/denite.rc.vim'
[[plugins]]
repo = 'Shougo/context_filetype.vim'
[[plugins]]
repo = 'simeji/winresizer'
[[plugins]]
repo = "machakann/vim-highlightedyank"
[[plugins]]
repo = "edkolev/tmuxline.vim"
hook_add = 'source ~/.vim/userautoload/plugins/tmuxline.rc.vim'
[[plugins]]
repo = "christoomey/vim-tmux-navigator"
[[plugins]]
repo = 'Shougo/echodoc.vim'
hook_add = 'source ~/.vim/userautoload/plugins/echodoc.rc.vim'
[[plugins]]
repo = 'mbbill/undotree'
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = 'source ~/.vim/userautoload/plugins/coc.rc.vim'
[[plugins]]
repo = 'neoclide/coc-denite'
depends = ['coc.nvim']
