[[plugins]]
repo = 'mattn/emmet-vim'
hook_source = '''
  let g:user_emmet_expandabbr_key='<Tab>'
  autocmd FileType html,css,scss,sass EmmetInstall
'''
on_ft = ['html', 'vue', 'css', 'scss', 'sass']

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_source = '''
  let g:vimtex_compiler_progname = 'nvr'
  let g:vimtex_view_method = 'zathura'
'''
