[[plugins]]
repo = 'craigemery/vim-autotag'
hook_source = '''
  let g:autotagTagsFile="tags"
'''
on_ft = ['c', 'cpp']
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = '''
  call deoplete#enable()
  source ~/.vim/userautoload/plugins/deoplete.rc.vim
'''
[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_event = 'InsertCharPre'
hook_source = 'source ~/.vim/userautoload/plugins/neosnippet.rc.vim'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1
[[plugins]]
repo = 'mattn/emmet-vim'
hook_source = '''
  let g:user_emmet_expandabbr_key='<Tab>'
  autocmd FileType html,css,scss,sass EmmetInstall
'''
on_ft = ['html', 'css', 'scss', 'sass']
